[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
name = "summit_rcm"
version = "14.25.0.1"
description = "Summit Remote Control Manager (RCM)"
license = "LicenseRef-Ezurio-Clause"
license-files = ["LICENSE.ezurio"]
dependencies = ["aiofiles", "dbus-fast", "pyroute2>=0.9.1"]

[project.optional-dependencies]
web = ["uvicorn", "falcon"]
at-interface = ["pyserial-asyncio", "transitions"]
bluetooth = ["pyudev", "websockets"]
docs = ["mkdocs", "mkdocs-material", "falcon", "pydantic", "spectree"]